version: '3'

tasks:
  templ: go tool templ generate

  build:
    deps: [templ]
    env:
      CGO_ENABLED: 0
    cmd: go build -ldflags "-X github.com/shimmerglass/musikat/version.Version=${VERSION:-dev}" .

  build-all:
     deps: [templ]
     cmds:
      - for:
          matrix:
            OS: ['windows', 'linux', 'darwin']
            ARCH: ['amd64', 'arm64']

        cmd: |
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} \
          go build \
          -ldflags "-X github.com/shimmerglass/musikat/version.Version=${VERSION:-dev}" \
          -o bin/musikat-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}{{ if eq .ITEM.OS "windows" }}.exe{{ end }} \
          .

  run:
    deps: [build]
    dotenv:
      - .env
    cmd: ./musikat

  test:
    deps: [templ]
    cmds:
      - go test -timeout 3m ./...
      - go tool errcheck ./...
      - go tool ineffassign ./...
